/**
 * Cloudflare Pages post-build script.
 *
 * Cloudflare Pages needs a `_worker.js` in the static assets directory to run
 * server-side code. This script finds the worker-entry bundle produced by Vite
 * and copies it (plus all server assets) so Pages can use it.
 *
 * It also writes `_routes.json` to send every request through the Worker.
 */

import { readFileSync, writeFileSync, cpSync, readdirSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

const CLIENT_DIR = join("dist", "client");
const SERVER_DIR = join("dist", "server");
const SERVER_ASSETS = join(SERVER_DIR, "assets");

// 1. Find the worker-entry bundle
let workerEntryFile = null;
for (const f of readdirSync(SERVER_ASSETS)) {
  if (f.startsWith("worker-entry") && f.endsWith(".js")) {
    workerEntryFile = join(SERVER_ASSETS, f);
    break;
  }
}

if (!workerEntryFile) {
  console.error("❌ Could not find worker-entry bundle in", SERVER_ASSETS);
  process.exit(1);
}

// 2. Copy all server assets into client dir (worker-entry imports them)
const serverAssetsInClient = join(CLIENT_DIR, "assets");
if (!existsSync(serverAssetsInClient)) mkdirSync(serverAssetsInClient, { recursive: true });

for (const f of readdirSync(SERVER_ASSETS)) {
  // skip files already in client assets
  const destPath = join(CLIENT_DIR, "assets", f);
  if (!existsSync(destPath)) {
    cpSync(join(SERVER_ASSETS, f), destPath);
  }
}

// 3. Write _worker.js — this is the Pages SSR entry point
//    The worker-entry bundle exports `workerEntry` as named export `w`
const workerEntryFilename = workerEntryFile.split("/").pop();
const workerJs = `// Auto-generated by scripts/postbuild-pages.js
import { w as workerEntry } from "./assets/${workerEntryFilename}";
export default workerEntry;
`;
writeFileSync(join(CLIENT_DIR, "_worker.js"), workerJs);
console.log("✅ _worker.js written");

// 4. Write _routes.json
// Static assets (/assets/*) are served directly by Pages from the bucket.
// Only HTML routes go through the Worker for SSR.
const routes = {
  version: 1,
  include: ["/*"],
  exclude: ["/assets/*", "/sitemap.xml", "/robots.txt"],
};
writeFileSync(join(CLIENT_DIR, "_routes.json"), JSON.stringify(routes, null, 2));
console.log("✅ _routes.json written");

// 5. Write sitemap.xml
const now = new Date().toISOString().split("T")[0];
const DOMAIN = "https://rossettimichele.com";
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${DOMAIN}/</loc>
    <lastmod>${now}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`;
writeFileSync(join(CLIENT_DIR, "sitemap.xml"), sitemap);
console.log("✅ sitemap.xml written");

// 6. Write robots.txt (allow all, point to sitemap)
const robots = `User-agent: *\nAllow: /\nSitemap: ${DOMAIN}/sitemap.xml\n`;
writeFileSync(join(CLIENT_DIR, "robots.txt"), robots);
console.log("✅ robots.txt written");
