/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminGithubRouteImport } from './routes/admin/github'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminSectionsIdRouteImport } from './routes/admin/sections.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGithubRoute = AdminGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsIdRoute = AdminSectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/sections': typeof AdminSectionsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/sections/$id': typeof AdminSectionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/sections': typeof AdminSectionsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/sections/$id': typeof AdminSectionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/github': typeof AdminGithubRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/sections': typeof AdminSectionsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/sections/$id': typeof AdminSectionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/admin/account'
    | '/admin/github'
    | '/admin/messages'
    | '/admin/sections'
    | '/admin/'
    | '/admin/sections/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/admin/account'
    | '/admin/github'
    | '/admin/messages'
    | '/admin/sections'
    | '/admin'
    | '/admin/sections/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/admin/account'
    | '/admin/github'
    | '/admin/messages'
    | '/admin/sections'
    | '/admin/'
    | '/admin/sections/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/github': {
      id: '/admin/github'
      path: '/github'
      fullPath: '/admin/github'
      preLoaderRoute: typeof AdminGithubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections/$id': {
      id: '/admin/sections/$id'
      path: '/$id'
      fullPath: '/admin/sections/$id'
      preLoaderRoute: typeof AdminSectionsIdRouteImport
      parentRoute: typeof AdminSectionsRoute
    }
  }
}

interface AdminSectionsRouteChildren {
  AdminSectionsIdRoute: typeof AdminSectionsIdRoute
}

const AdminSectionsRouteChildren: AdminSectionsRouteChildren = {
  AdminSectionsIdRoute: AdminSectionsIdRoute,
}

const AdminSectionsRouteWithChildren = AdminSectionsRoute._addFileChildren(
  AdminSectionsRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminGithubRoute: typeof AdminGithubRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSectionsRoute: typeof AdminSectionsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminGithubRoute: AdminGithubRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSectionsRoute: AdminSectionsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
